### ISSUE TITLE
Resource Warning

### ISSUE THREAD

**Issue by alexandermarston** [jaxxstorm/pulumi-rke#45]
I am using the RKE provider in a TypeScript project. All works fine, but when I run ``pulumi up`` I get the following warnings:

````
  pulumi:pulumi:Stack (iac-dev):
    warning: resource plugin rke is expected to have version >=2.0.0, but has ; the wrong version may be on your path, or this may be a bug in the plugin
    warning: resource plugin rke is expected to have version >=2.0.0, but has ; the wrong version may be on your path, or this may be a bug in the plugin
    error: update failed
````

````
alex$ pulumi plugin ls
NAME        KIND      VERSION  SIZE   INSTALLED     LAST USED
rke         resource  2.0.0    69 MB  2 days ago    2 days ago
````

````
    "dependencies": {
        "@jaxxstorm/pulumi-rke": ">=2.0.0",
        "@pulumi/gcp": "^3.7.1",
        "@pulumi/kubernetes": "^2.2.2",
        "@pulumi/pulumi": "^2.3.0"
    }
````

Is this something I am doing wrong or an issue with the plugin?

**Comment by mitchellmaler** [comment]
Have you built this plugin yourself for other versions or just copy it into the pulumi plugins directory?
I have had issues where I built the plugin so it added it to my go bin directly. Even if the pulumi plugin ls shows one in its directly when running the stack it evaulates against your PATH so if the go bin is first with an older version that is used.

**Comment by alexandermarston** [comment]
I have not been installing the plugin manually. I installed the plugin using the `pulumi plugin install` command.

````
> pulumi plugin install resource rke 2.0.0 --server https://github.com/jaxxstorm/pulumi-rke/releases/download/v2.0.0/
[resource plugin rke-2.0.0] installing
Downloading plugin: 26.60 MiB / 26.60 MiB [=========================] 100.00% 6s
Moving plugin... done.
````

Is that the right way to do it?

**Comment by mitchellmaler** [comment]
Oh yea that is the right way. I haven't tested the latest version but just know I have seen it in the past when I had multiple versions installed and in different paths. Looking at the error it might just be the plugin doesn't have the version set then it doesn't return a version at all in the message.

I was planning on upgrading my stack to 2.0.0 and if I see the same issue I'll reply here.

**Comment by alexandermarston** [comment]
@jaxxstorm any chance you could have a look at this one please? Thanks

**Comment by donovanmuller** [comment]
I have the same issue, the `rke` resource plugin is missing the version (or is blank):

```console
$ pulumi plugin install resource rke 2.0.0 --server https://github.com/jaxxstorm/pulumi-rke/releases/download/v2.0.0/
[resource plugin rke-2.0.0] installing
Downloading plugin: 26.60 MiB / 26.60 MiB [=========================] 100.00% 9s
Moving plugin... done.

$ cd ~/.pulumi/plugins/resource-rke-v2.0.0
$ ./pulumi-resource-rke -version
# missing version...
```

compare that to another resource plugin returning a version:

```console
$ pwd
~/.pulumi/plugins/resource-packet-v2.2.2
$ ./pulumi-resource-packet -version
v2.2.2
```

this causes the following error when running `pulumi up`:

```console
$ pulumi up --yes
Previewing update (xxx):
     Type                  Name                       Plan     Info
     pulumi:pulumi:Stack   xxx                                 4 messages
     └─ rke:index:Cluster  test                                1 error

Diagnostics:
  rke:index:Cluster (test):
    error: unrecognized resource type (Check): rke:index/cluster:Cluster
...
```

Additionally, I had to install the resource plugin [manually](https://github.com/jaxxstorm/pulumi-rke/issues/45#issuecomment-637011412) (was not installed automatically on first run...)

**Comment by jaxxstorm** [comment]
@donovanmuller the automatic install is expected.

I'm working on a new release of the provider now which should hopefully fix some of these issues, thanks for your patience.

**Comment by jaxxstorm** [comment]
@donovanmuller @mitchellmaler @alexandermarston I've published a beta version to nuget and to the releases, please give it a try and see if it resolves your issues. If it does, I'll publish a proper version.

**Comment by donovanmuller** [comment]
@jaxxstorm with the following:

```console
$ go get github.com/jaxxstorm/pulumi-rke/sdk/v2/go/...
$ cat go.mod
...
require (
	github.com/jaxxstorm/pulumi-rke/sdk/v2 v2.0.0-20200622042604-c09f47d0d6f2
	github.com/pulumi/pulumi-packet/sdk/v2 v2.2.2
	github.com/pulumi/pulumi/sdk/v2 v2.3.1-0.20200607162109-9754465b04db
	golang.org/x/crypto v0.0.0-20200317142112-1b76d66859c6
)
```

and removing the old and adding the new resource plugin:

```console
$ pulumi plugin rm resource rke 2.0.0
$ pulumi plugin install resource rke 2.1.0-alpha --server https://github.com/jaxxstorm/pulumi-rke/releases/download/v2.1.0-alpha

$ pulumi plugin ls
NAME    KIND      VERSION      SIZE   INSTALLED       LAST USED
packet  resource  2.2.2        39 MB  20 hours ago    20 hours ago
rke     resource  2.1.0-alpha  68 MB  29 minutes ago  15 minutes ago
```

I still get:

```console
$ pulumi up --yes
...
Diagnostics:
  rke:index:Cluster (test):
    error: unrecognized resource type (Check): rke:index/cluster:Cluster
```

not sure how the resource plugin version gets referenced from the provider so not sure where to go from here?

**Comment by jaxxstorm** [comment]
Can you post the cluster definition? (ie, the code you're using to define your cluster?)

**Comment by donovanmuller** [comment]
Sample Go SDK program that uses Packet for nodes: https://gist.github.com/donovanmuller/a7575815f8cd62222bb5c8b6e264abdb

```console
$ pulumi up
pulumi up
Previewing update (test-dev):
     Type                           Name           Plan       Info
 +   pulumi:pulumi:Stack            test-test-dev  create     1 message
 +   ├─ packet:index:Project        test           create
 +   ├─ packet:index:ProjectSshKey  default        create
 +   ├─ packet:index:Device         node1          create
     └─ rke:index:Cluster           test                      1 error

Diagnostics:
  rke:index:Cluster (test):
    error: unrecognized resource type (Check): rke:index/cluster:Cluster

  pulumi:pulumi:Stack (test-test-dev):
    2020/06/22 21:57:29 [DEBUG] GET https://api.packet.net/operating-systems
```

**Comment by jaxxstorm** [comment]
Thanks, I'm really not sure where that's coming from. I don't see any reference to it in the schema. I'm going to try write some integration tests this week, so hopefully it'll bubble up through there.
